name: Restart Bot

on:
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_MOUNTAIN_SERVER }}
          name: id_mountain
          known_hosts: ${{ secrets.KNOWN_HOSTS_MOUNTAIN_SERVER }}
          config: ${{ secrets.CONFIG_MOUNTAIN_SERVER }}
      - name: Run restart script
        shell: bash -xe {0}
        env:
          PASSWORD: ${{ secrets.PASSWORD_MOUNTAIN_SERVER }}
        run: |
          cd "${GITHUB_WORKSPACE}"
          ls -a
          chmod +x "/.github/script/restart.sh"
          "/.github/restart.sh ${PASSWORD}"
