name: Update Bot

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_MOUNTAIN_SERVER }}
          name: id_mountain
          known_hosts: ${{ secrets.KNOWN_HOSTS_MOUNTAIN_SERVER }}
          config: ${{ secrets.CONFIG_MOUNTAIN_SERVER }}
      - name: Run update script
        shell: bash -xe {0}
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          MODERATOR_ROLE_ID: ${{ secrets.MODERATOR_ROLE_ID }}
          LOGDNA_TOKEN: ${{ secrets.LOGDNA_TOKEN }}
          LOGDNA_APP: ${{ secrets.LOGDNA_APP }}
          PASSWORD: ${{ secrets.PASSWORD_MOUNTAIN_SERVER }}
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/script/update.sh"
          ${GITHUB_WORKSPACE}/.github/script/update.sh ${PASSWORD} ${ENV} ${DISCORD_BOT_TOKEN} ${MODERATOR_ROLE_ID} ${LOGDNA_TOKEN} ${LOGDNA_APP} ${SENDGRID_API_KEY} ${SENDGRID_FROM_EMAIL} ${DENDAI_EMAIL_DOMAIN} ${DB_HOST} ${DB_USERNAME} ${DB_PASSWORD} ${DB_DATABASE}
